const express = require('express')

const { createUser, loginCtrl, getallUser, getaUser, deletedaUser, updatedaUser, blockUser, unblockUser, handleRefreshToken, handlelogout, updatePassword, forgetPasswordToken, resetPassword, adminLogin, getWishList, saveAddress, userCart, getUserCart, emptyCart, appliedCoupon, createOrder, updateOrderStatus, getMonthWiseIncom, getYearlyOrder, getAllOrders, getSingleOrder, removeproductFromCart, updateprodquantCart, myOrder, getAllOrder, getAOrder } = require('../controller/userCtrl')
const { authMiddleware, isAdmin } = require('../middleware/authMiddleware')
const router = express.Router()


router.post('/register',createUser)
router.post('/login', loginCtrl)
router.post('/adminlogin', adminLogin)
router.post('/forgetPassword', forgetPasswordToken)
router.put('/reset-Password/:token', resetPassword)
router.get('/refreshToken', handleRefreshToken)
router.get('/logout', handlelogout)
router.post('/cart', authMiddleware, userCart)
router.post('/cart/createOrder', authMiddleware, createOrder)
router.get('/wishlist', authMiddleware, getWishList)
router.get('/getcart', authMiddleware, getUserCart)
router.put('/saveaddress', authMiddleware, saveAddress)
router.put('/updatePassword', authMiddleware, updatePassword)
router.get('/getUser', authMiddleware, isAdmin, getallUser)
router.get('/getOrder', authMiddleware, myOrder)
router.get('/getOrders', authMiddleware, getAllOrder)
router.get('/getOrder/:id', authMiddleware, getAOrder)
router.get('/getMonth', authMiddleware, isAdmin, getMonthWiseIncom)
router.get('/getyearly', authMiddleware, isAdmin, getYearlyOrder)
router.get('/:id', getaUser)
router.delete('/removecart/:cartItemId', authMiddleware, removeproductFromCart)
router.put('/updatecart/:cartItemId/:newQuantity', authMiddleware, updateprodquantCart)
router.delete('/:id',deletedaUser)
router.put('/edit_user',authMiddleware, updatedaUser)
router.put('/block_user/:id',authMiddleware,isAdmin, blockUser)
router.put('/isblock_user/:id',authMiddleware, isAdmin, unblockUser)
// router.put('/order/update-order-status/:id',authMiddleware, isAdmin, updateOrderStatus)
module.exports = router